version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        volumes:
            - ./mysql-dump:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: profilems
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "6603:3306"
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8081:80"
    web:
        depends_on: 
            - db
        image: tomcat:9.0.10
        container_name: tomcat
        volumes:
            - ./target/ProfileManagement.war:/usr/local/tomcat/webapps/ProfileManagement.war
        restart: always
        ports:
            - '8080:8080'
        environment: 
            JDBC_URL: jdbc:mysql://db:3306/
            DATABASE_NAME: profilems
            JDBC_USER: user
            JDBC_PASS: pass
